# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20151214_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='statement',
        ),
    ]
