# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20151214_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'True/false question', 'verbose_name_plural': 'True/false questions'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='intro',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.BooleanField(verbose_name='True?'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
